package wrapper

import (
	"net/http"
	"net/http/httptest"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

const sampleSHASums = `
# generated by release pipeline; do not edit
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa  busybae-darwin_arm64.tar.gz
bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb  busybae-darwin_amd64.tar.gz
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc  busybae-linux_arm64.tar.gz
dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd  busybae-linux_amd64.tar.gz
eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee  busybae-windows_amd64.zip
`

func TestParseSHAs(t *testing.T) {
	got, err := parseSHAs(strings.NewReader(sampleSHASums))
	if err != nil {
		t.Fatal(err)
	}
	want := map[string]string{
		"darwin_arm64": strings.Repeat("a", 64),
		"darwin_amd64": strings.Repeat("b", 64),
		"linux_arm64":  strings.Repeat("c", 64),
		"linux_amd64":  strings.Repeat("d", 64),
	}
	for k, v := range want {
		if got[k] != v {
			t.Errorf("%s: got %q, want %q", k, got[k], v)
		}
	}
	// The Windows entry must be ignored, not surface as an error.
	if _, ok := got["windows_amd64"]; ok {
		t.Error("unexpected windows entry")
	}
}

func TestParseSHAsMissingPlatform(t *testing.T) {
	partial := `aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa  busybae-darwin_arm64.tar.gz`
	_, err := parseSHAs(strings.NewReader(partial))
	if err == nil {
		t.Fatal("expected error for missing platforms")
	}
	if !strings.Contains(err.Error(), "linux_amd64") {
		t.Fatalf("error should mention missing platforms, got %v", err)
	}
}

func TestParseSHAsHandlesBinaryModeStar(t *testing.T) {
	src := `aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa *busybae-darwin_arm64.tar.gz
bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb *busybae-darwin_amd64.tar.gz
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc *busybae-linux_arm64.tar.gz
dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd *busybae-linux_amd64.tar.gz`
	got, err := parseSHAs(strings.NewReader(src))
	if err != nil {
		t.Fatal(err)
	}
	if got["darwin_arm64"] != strings.Repeat("a", 64) {
		t.Fatalf("binary-mode * not stripped: %v", got)
	}
}

func TestInstallWritesWrapper(t *testing.T) {
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if !strings.HasSuffix(r.URL.Path, "/v0.1.2/SHA256SUMS") {
			t.Errorf("unexpected fetch path: %s", r.URL.Path)
		}
		_, _ = w.Write([]byte(sampleSHASums))
	}))
	defer srv.Close()

	dir := t.TempDir()
	out := filepath.Join(dir, "tools", "bazel")

	err := Install(Options{
		Version:    "0.1.2",
		ReleaseURL: srv.URL,
		Out:        out,
		HTTPClient: srv.Client(),
	})
	if err != nil {
		t.Fatal(err)
	}
	got, err := os.ReadFile(out)
	if err != nil {
		t.Fatal(err)
	}
	body := string(got)
	// Spot-check the rendered pins.
	for _, snippet := range []string{
		`BUSYBAE_VERSION="0.1.2"`,
		`"darwin_arm64") sha="` + strings.Repeat("a", 64) + `"`,
		`"linux_amd64") sha="` + strings.Repeat("d", 64) + `"`,
		`BUSYBAE_DISABLE`,
		`${CI:-}`,
		`BAZELISK_SKIP_WRAPPER=true`,
	} {
		if !strings.Contains(body, snippet) {
			t.Errorf("wrapper missing %q\n---\n%s", snippet, body)
		}
	}
	// Wrapper must be executable.
	info, err := os.Stat(out)
	if err != nil {
		t.Fatal(err)
	}
	if info.Mode().Perm()&0o111 == 0 {
		t.Fatalf("wrapper not executable: %v", info.Mode())
	}
}

func TestInstallRejectsDevVersion(t *testing.T) {
	err := Install(Options{Version: "dev"})
	if err == nil || !strings.Contains(err.Error(), "stamped") {
		t.Fatalf("expected stamped-version error, got %v", err)
	}
}

func TestInstallCheckDetectsDrift(t *testing.T) {
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, _ *http.Request) {
		_, _ = w.Write([]byte(sampleSHASums))
	}))
	defer srv.Close()

	dir := t.TempDir()
	out := filepath.Join(dir, "tools", "bazel")
	if err := os.MkdirAll(filepath.Dir(out), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(out, []byte("# stale\n"), 0o755); err != nil {
		t.Fatal(err)
	}

	err := Install(Options{
		Version:    "0.1.2",
		ReleaseURL: srv.URL,
		Out:        out,
		Check:      true,
		HTTPClient: srv.Client(),
	})
	if err == nil || !strings.Contains(err.Error(), "out of date") {
		t.Fatalf("expected drift error, got %v", err)
	}

	// After regenerating, --check should succeed.
	if err := Install(Options{
		Version:    "0.1.2",
		ReleaseURL: srv.URL,
		Out:        out,
		HTTPClient: srv.Client(),
	}); err != nil {
		t.Fatal(err)
	}
	if err := Install(Options{
		Version:    "0.1.2",
		ReleaseURL: srv.URL,
		Out:        out,
		Check:      true,
		HTTPClient: srv.Client(),
	}); err != nil {
		t.Fatalf("check after write: %v", err)
	}
}

func TestInstallSHAFile(t *testing.T) {
	dir := t.TempDir()
	sumFile := filepath.Join(dir, "SHA256SUMS")
	if err := os.WriteFile(sumFile, []byte(sampleSHASums), 0o600); err != nil {
		t.Fatal(err)
	}
	out := filepath.Join(dir, "tools", "bazel")
	err := Install(Options{
		Version: "0.1.2",
		SHAFile: sumFile,
		Out:     out,
	})
	if err != nil {
		t.Fatal(err)
	}
	body, err := os.ReadFile(out)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(body), strings.Repeat("a", 64)) {
		t.Fatal("SHA from local file not used")
	}
}
